# Site settings
author: James
title: Data Science Journey
header-img: img/home-bg.png
email: jamesbrockbrochhausen@gmail.com
copyright_name: James
description: > # this means to ignore newlines until "baseurl:"
  Personal journey of someone entering Data Science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jamesbrockb

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
